FROM python:3

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app/
RUN pip install -r requirements.txt
COPY . /usr/src/app

EXPOSE 8000
CMD [ "./entrypoint.sh" ]